export const DRIVER_HOME_DEFAULT_CENTER = {
  lat: -12.5458,
  lon: -55.7061,
} as const;

export const DRIVER_HOME_CACHE_KEYS = {
  DRIVER_LOCATION: '@vamu:driver_location',
  DRIVER_LOCATION_TIMESTAMP: '@vamu:driver_location_timestamp',
  DRIVER_AVAILABILITY_PREF: '@vamu:driver_availability_pref',
  ACTIVE_TRIP_ID: '@vamu:active_trip_id',
  ACTIVE_TRIP_DATA: '@vamu:active_trip_data',
  PAYMENT_METHODS: '@vamu:payment_methods',
  PAYMENT_BRANDS: '@vamu:payment_brands',
} as const;

export const DRIVER_HOME_TIMERS = {
  CACHE_VALIDITY_MS: 5 * 60 * 1000,
  LOCATION_REQUEST_THROTTLE_MS: 30 * 1000,
  LOCATION_STALE_MS: 2 * 60 * 1000,
  LAST_KNOWN_MAX_AGE_MS: 3 * 60 * 1000,
  LOCATION_LOOP_MS: 3000,
  NEARBY_LOOP_MS: 30000,
  CACHE_SAVE_THROTTLE_MS: 15000,
  AVAILABILITY_WINDOW_MS: 60000,
  AVAILABILITY_DELAY_MS: 60000,
  DOUBLE_SEND_DELAY_MS: 300,
  ACTIVE_RIDE_CHECK_DELAY_MS: 2000,
  LOCATION_REFRESH_ON_FOCUS_DELAY_MS: 150,
  OFFER_DEFAULT_EXPIRE_MS: 15000,
} as const;

export const DRIVER_HOME_ZOOM_LEVELS = [12, 14, 16, 18, 20] as const;

export const ACTIVE_PASSENGER_STATUSES = ['REQUESTED', 'DRIVER_ASSIGNED', 'DRIVER_ARRIVING'] as const;

export const TERMINAL_RIDE_STATUSES = [
  'CANCELADA_MOTORISTA',
  'CANCELADA_PASSAGEIRO',
  'CANCELADA_ADMIN',
  'CANCELLED',
  'CANCELED_BY_DRIVER',
  'CANCELED_BY_PASSENGER',
  'EXPIRED',
  'COMPLETED',
  'CONCLUIDA',
  'CORRIDA_FINALIZADA',
  'AGUARDANDO_AVALIACAO',
] as const;
